### PR TITLE
Create Gymea.md

### LINKED ISSUE #8: An issue about issues
We are about to have too many issues.
- [x] Make too many issues
- [x] Resolve some
- [x] Use some emojis :cry: 
- [x] Find peace

### PR DESCRIPTION
**Pull request by 1rgy**
because the teacher said to.

Fixes #8

### CODE REVIEW

**Review by stevew21 — COMMENTED** [review]
Where to eat in Gymea

**Comment by 1rgy** [comment]
@stevew21 I've added food places is it good now?

**Comment by chrisr12** [comment]
Looks good to me.

**Comment by stevew21** [comment]
Ok

**Pull request closed without merging**
