### PR TITLE
Add Allen's hometown

### LINKED ISSUE #10: Allen's issues
## Checklist
- [x] Create an issue - what? another one?
- [ ] ???
- [ ] profit!

### PR DESCRIPTION
**Pull request by allenc23**
Fixes #10

### CODE REVIEW

**Review by amiguptapro — CHANGES_REQUESTED** [review]
changes requested. Please add your street address.

**Comment by allenc23** [comment]
Will this do?

**Review by pqtuan — APPROVED** [review]
LGTM :ship:

**Review by amiguptapro — APPROVED** [review]
LGBT :shipit:

**Pull request merged**
