### PR TITLE
Pqtuan ryde

### LINKED ISSUE #5: Issue #N
- [x] are we done yet?

### PR DESCRIPTION
**Pull request by pqtuan**
fixed #5

### CODE REVIEW

**Comment by pqtuan** [comment]
Could you review my stuff? thks. Tuan

**Review by chcao052 — COMMENTED** [review]
look good

**Comment by pqtuan** [comment]
Chris, how can I bribe you to approve my stuffs?

**Review by chcao052 — APPROVED** [review]
:ship:

**Comment by pqtuan** [comment]
Yahoo, merged, now delete branch

**Review by chrisr12 — COMMENTED** [review]
The changes look good. No bribe needed!

**Review by chrisr12 — COMMENTED** [review]
hmm.. I don't see the 'approve' option below this review..

**Pull request merged**
